#!/usr/bin/env bash

set -euo pipefail

export MAX_TOKENS=1000
export MODEL="claude-3-5-haiku-20241022"
export INPUT_TOKEN_COST_CENTS="0.00008"
export OUTPUT_TOKEN_COST_CENTS="0.0004"
SOURCE_DIR="$(dirname $0)"
$SOURCE_DIR/claude
