#!/usr/bin/env bash

set -euo pipefail

export MAX_TOKENS=1000
export MODEL="claude-3-7-sonnet-20250219"
export INPUT_TOKEN_COST_CENTS="0.0003"
export OUTPUT_TOKEN_COST_CENTS="0.0015"
SOURCE_DIR="$(dirname $0)"
$SOURCE_DIR/claude
