#!/usr/bin/env bash

set -euo pipefail

export MAX_TOKENS=1000
export MODEL="gpt-3.5-turbo-0125"
export INPUT_TOKEN_COST_CENTS="0.00005"
export OUTPUT_TOKEN_COST_CENTS="0.00015"
SOURCE_DIR="$(dirname $0)"
$SOURCE_DIR/gpt
