#!/usr/bin/env bash

set -euo pipefail

export MAX_TOKENS=1000
export MODEL="gpt-4o-mini-2024-07-18"
export INPUT_TOKEN_COST_CENTS="0.000015"
export OUTPUT_TOKEN_COST_CENTS="0.000060"
SOURCE_DIR="$(dirname $0)"
$SOURCE_DIR/gpt
