#!/usr/bin/env bash

set -euo pipefail

export MAX_TOKENS=1000
export MODEL="gpt-5-2025-08-07"
export INPUT_TOKEN_COST_CENTS="0.000125"
export OUTPUT_TOKEN_COST_CENTS="0.001"
SOURCE_DIR="$(dirname $0)"
$SOURCE_DIR/gpt
