#!/usr/bin/env bash

set -euo pipefail

export MAX_TOKENS=1000
export MODEL="gemini-2.5-pro-exp-03-25"
export INPUT_TOKEN_COST_CENTS="0.000125"
export OUTPUT_TOKEN_COST_CENTS=".001"
SOURCE_DIR="$(dirname $0)"
$SOURCE_DIR/gemini
